In [3]:
import pandas as pd 

df1 = pd.read_csv('./files/origin.csv', index_col='Date')
df1

              open    high     low   close   volume  stock_code
Date
2024-05-13  110636  110910  110541  110801   110314      133690
2024-05-13   14705   14735   14640   14665    66604      132030
2024-05-13   37187   37276   36848   37013  5709470       69500
2024-05-13   11820   11845   11780   11800    57658      305080
2024-05-13  110795  110875  110725  110780     7228      148070
...            ...     ...     ...     ...      ...         ...
2024-10-08   34605   34725   34440   34620  2975544       69500
2024-10-08  115875  116000  115540  116000    11253      148070
2024-10-08   12070   12110   12020   12095    62380      305080
2024-10-08  118940  119225  118670  118990   287391      133690
2024-10-08   16170   16210   16120   16170   125670      132030

[495 rows x 6 columns]

In [12]:
date = df1.iloc[-1].name
stock_code = 305080

#combined_df.index == date
condition = (df1.index == date) & (df1['stock_code'] == stock_code)
df1[condition]

             open   high    low  close  volume  stock_code
Date
2024-10-08  12070  12110  12020  12095   62380      305080

In [ ]:
#sepa_69500.csv

In [ ]:
path = './files/'
invest_list = [69500, 148070, 305080, 133690, 132030]

for code in invest_list:
    stock_data = pd.read_csv(path + 'sepa_' + str(code) + '.csv', index_col='Date')
    print(code, '\n', stock_data)

In [20]:
path = './files/'
invest_list = [69500, 148070, 305080, 133690, 132030]

stock_df_list = []

for code in invest_list:
    df = pd.read_csv(path + 'sepa_' + str(code) + '.csv', index_col='Date')

    df['prevClose'] = df['close'].shift(1)
    
    ############# 이동평균선! ###############
    ma_dfs = []

    # 이동 평균 계산
    for ma in range(3, 21):
        ma_df = df['close'].rolling(ma).mean().rename(str(ma) + 'ma_before').shift(1)
        ma_dfs.append(ma_df)
        
        ma_df = df['close'].rolling(ma).mean().rename(str(ma) + 'ma_before2').shift(2)
        ma_dfs.append(ma_df)
    # 이동 평균 데이터 프레임을 하나로 결합
    ma_df_combined = pd.concat(ma_dfs, axis=1)
    # print(ma_df_combined)


    # 원본 데이터 프레임과 결합
    df = pd.concat([df, ma_df_combined], axis=1)
    print(df)
    ########################################

    #200거래일 평균 모멘텀
    specific_days = list()

    for i in range(1,2):
        st = i * 20
        specific_days.append(st)

    for day in specific_days:
        column_name = f'Momentum_{day}'
        df[column_name] = (df['prevClose'] > df['close'].shift(day)).astype(int)
    
    print(df)
        
        
'''
    df['Average_Momentum'] = df[[f'Momentum_{day}' for day in specific_days]].sum(axis=1) / 10
    
    df.dropna(inplace=True) #데이터 없는건 날린다!

    data_dict = {stock_code: df}
    stock_df_list.append(data_dict)
        
    print("---stock_code---", stock_code , " len ",len(df))
    
    pprint.pprint(df)

combined_df = pd.concat([list(data_dict.values())[0].assign(stock_code=stock_code) for data_dict in stock_df_list for stock_code in data_dict])
combined_df.sort_index(inplace=True)
pprint.pprint(combined_df)
print(" len(combined_df) ", len(combined_df))

date = combined_df.iloc[-1].name
'''

             open   high    low  close   volume  prevClose    3ma_before  \
Date
2024-05-13  37187  37276  36848  37013  5709470        NaN           NaN
2024-05-14  37112  37142  36968  37088  6339932    37013.0           NaN
2024-05-16  37719  37799  37411  37441  6520514    37088.0           NaN
2024-05-17  37366  37396  36998  37003  4735174    37441.0  37180.666667
2024-05-20  37331  37546  37207  37312  4464858    37003.0  37177.333333
...           ...    ...    ...    ...      ...        ...           ...
2024-09-30  35760  35830  34720  34720  7175102    35535.0  35245.000000
2024-10-02  34160  34670  34095  34355  6121360    34720.0  35311.666667
2024-10-04  34270  34640  34140  34340  6396033    34355.0  34870.000000
2024-10-07  34425  34975  34175  34885  5638671    34340.0  34471.666667
2024-10-08  34605  34725  34440  34620  2975544    34885.0  34526.666667

             3ma_before2  4ma_before  4ma_before2  ...  16ma_before  \
Date                                               ...
2024-05-13           NaN         NaN          NaN  ...          NaN
2024-05-14           NaN         NaN          NaN  ...          NaN
2024-05-16           NaN         NaN          NaN  ...          NaN
2024-05-17           NaN         NaN          NaN  ...          NaN
2024-05-20  37180.666667    37136.25          NaN  ...          NaN
...                  ...         ...          ...  ...          ...
2024-09-30  35078.333333    35192.50     34963.75  ...   34663.1250
2024-10-02  35245.000000    35113.75     35192.50  ...   34585.9375
2024-10-04  35311.666667    35072.50     35113.75  ...   34564.0625
2024-10-07  34870.000000    34737.50     35072.50  ...   34544.6875
2024-10-08  34471.666667    34575.00     34737.50  ...   34578.7500

            16ma_before2   17ma_before  17ma_before2   18ma_before  \
Date
2024-05-13           NaN           NaN           NaN           NaN
2024-05-14           NaN           NaN           NaN           NaN
2024-05-16           NaN           NaN           NaN           NaN
2024-05-17           NaN           NaN           NaN           NaN
2024-05-20           NaN           NaN           NaN           NaN
...                  ...           ...           ...           ...
2024-09-30    34708.4375  34757.058824  34802.058824  34842.777778
2024-10-02    34663.1250  34666.470588  34757.058824  34755.000000
2024-10-04    34585.9375  34572.352941  34666.470588  34649.166667
2024-10-07    34564.0625  34550.882353  34572.352941  34559.444444
2024-10-08    34544.6875  34564.705882  34550.882353  34569.444444

            18ma_before2   19ma_before  19ma_before2  20ma_before  \
Date
2024-05-13           NaN           NaN           NaN          NaN
2024-05-14           NaN           NaN           NaN          NaN
2024-05-16           NaN           NaN           NaN          NaN
2024-05-17           NaN           NaN           NaN          NaN
2024-05-20           NaN           NaN           NaN          NaN
...                  ...           ...           ...          ...
2024-09-30  34874.722222  34909.473684  34965.263158     34993.75
2024-10-02  34842.777778  34836.315789  34909.473684     34900.00
2024-10-04  34755.000000  34733.947368  34836.315789     34812.25
2024-10-07  34649.166667  34632.894737  34733.947368     34714.25
2024-10-08  34559.444444  34576.578947  34632.894737     34645.50

            20ma_before2
Date
2024-05-13           NaN
2024-05-14           NaN
2024-05-16           NaN
2024-05-17           NaN
2024-05-20           NaN
...                  ...
2024-09-30      35043.50
2024-10-02      34993.75
2024-10-04      34900.00
2024-10-07      34812.25
2024-10-08      34714.25

[99 rows x 42 columns]
              open    high     low   close  volume  prevClose     3ma_before  \
Date
2024-05-13  110795  110875  110725  110780    7228        NaN            NaN
2024-05-14  110785  110930  110690  110910    4225   110780.0            NaN
2024-05-16  111800  111860  111680  111715   25324   110910.0            NaN
2024-05-17  111510  111865  111460  111715   18630   111715.0  111135.000000
2024-05-20  111465  111485  111245  111245    8949   111715.0  111446.666667
...            ...     ...     ...     ...     ...        ...            ...
2024-09-30  116825  117010  116715  116805   11403   116610.0  116631.666667
2024-10-02  117045  117415  117045  117335   32405   116805.0  116680.000000
2024-10-04  116765  116815  116610  116710   10361   117335.0  116916.666667
2024-10-07  116235  116235  115660  115740   15612   116710.0  116950.000000
2024-10-08  115875  116000  115540  116000   11253   115740.0  116595.000000

              3ma_before2  4ma_before  4ma_before2  ...  16ma_before  \
Date                                                ...
2024-05-13            NaN         NaN          NaN  ...          NaN
2024-05-14            NaN         NaN          NaN  ...          NaN
2024-05-16            NaN         NaN          NaN  ...          NaN
2024-05-17            NaN         NaN          NaN  ...          NaN
2024-05-20  111135.000000   111280.00          NaN  ...          NaN
...                   ...         ...          ...  ...          ...
2024-09-30  116590.000000   116595.00    116542.50  ...  116459.3750
2024-10-02  116631.666667   116675.00    116595.00  ...  116549.3750
2024-10-04  116680.000000   116843.75    116675.00  ...  116640.6250
2024-10-07  116916.666667   116865.00    116843.75  ...  116669.6875
2024-10-08  116950.000000   116647.50    116865.00  ...  116626.5625

            16ma_before2    17ma_before   17ma_before2    18ma_before  \
Date
2024-05-13           NaN            NaN            NaN            NaN
2024-05-14           NaN            NaN            NaN            NaN
2024-05-16           NaN            NaN            NaN            NaN
2024-05-17           NaN            NaN            NaN            NaN
2024-05-20           NaN            NaN            NaN            NaN
...                  ...            ...            ...            ...
2024-09-30   116386.8750  116400.000000  116348.529412  116363.055556
2024-10-02   116459.3750  116479.705882  116400.000000  116422.500000
2024-10-04   116549.3750  116595.588235  116479.705882  116527.222222
2024-10-07   116640.6250  116644.705882  116595.588235  116601.944444
2024-10-08   116669.6875  116615.000000  116644.705882  116594.444444

             18ma_before2    19ma_before   19ma_before2  20ma_before  \
Date
2024-05-13            NaN            NaN            NaN          NaN
2024-05-14            NaN            NaN            NaN          NaN
2024-05-16            NaN            NaN            NaN          NaN
2024-05-17            NaN            NaN            NaN          NaN
2024-05-20            NaN            NaN            NaN          NaN
...                   ...            ...            ...          ...
2024-09-30  116315.000000  116330.526316  116294.736842    116310.50
2024-10-02  116363.055556  116386.315789  116330.526316    116354.25
2024-10-04  116422.500000  116470.526316  116386.315789    116433.75
2024-10-07  116527.222222  116536.842105  116470.526316    116482.50
2024-10-08  116601.944444  116556.578947  116536.842105    116497.00

            20ma_before2
Date
2024-05-13           NaN
2024-05-14           NaN
2024-05-16           NaN
2024-05-17           NaN
2024-05-20           NaN
...                  ...
2024-09-30     116263.25
2024-10-02     116310.50
2024-10-04     116354.25
2024-10-07     116433.75
2024-10-08     116482.50

[99 rows x 42 columns]
             open   high    low  close  volume  prevClose    3ma_before  \
Date
2024-05-13  11820  11845  11780  11800   57658        NaN           NaN
2024-05-14  11800  11810  11785  11805   41872    11800.0           NaN
2024-05-16  11910  11910  11710  11715   72848    11805.0           NaN
2024-05-17  11715  11795  11690  11765   56612    11715.0  11773.333333
2024-05-20  11830  11830  11720  11720   50463    11765.0  11761.666667
...           ...    ...    ...    ...     ...        ...           ...
2024-09-30  11930  11930  11855  11885   72825    11965.0  12050.000000
2024-10-02  11950  12045  11950  12005   69095    11885.0  11970.000000
2024-10-04  12005  12080  12005  12065   63951    12005.0  11951.666667
2024-10-07  12090  12100  12035  12075  902138    12065.0  11985.000000
2024-10-08  12070  12110  12020  12095   62380    12075.0  12048.333333

             3ma_before2  4ma_before  4ma_before2  ...  16ma_before  \
Date                                               ...
2024-05-13           NaN         NaN          NaN  ...          NaN
2024-05-14           NaN         NaN          NaN  ...          NaN
2024-05-16           NaN         NaN          NaN  ...          NaN
2024-05-17           NaN         NaN          NaN  ...          NaN
2024-05-20  11773.333333    11771.25          NaN  ...          NaN
...                  ...         ...          ...  ...          ...
2024-09-30  12106.666667    12071.25     12117.50  ...   12135.3125
2024-10-02  12050.000000    12008.75     12071.25  ...   12123.4375
2024-10-04  11970.000000    11978.75     12008.75  ...   12114.6875
2024-10-07  11951.666667    11980.00     11978.75  ...   12110.0000
2024-10-08  11985.000000    12007.50     11980.00  ...   12109.0625

            16ma_before2   17ma_before  17ma_before2   18ma_before  \
Date
2024-05-13           NaN           NaN           NaN           NaN
2024-05-14           NaN           NaN           NaN           NaN
2024-05-16           NaN           NaN           NaN           NaN
2024-05-17           NaN           NaN           NaN           NaN
2024-05-20           NaN           NaN           NaN           NaN
...                  ...           ...           ...           ...
2024-09-30    12138.4375  12128.235294  12132.647059  12123.333333
2024-10-02    12135.3125  12120.588235  12128.235294  12114.722222
2024-10-04    12123.4375  12116.470588  12120.588235  12114.166667
2024-10-07    12114.6875  12111.764706  12116.470588  12113.611111
2024-10-08    12110.0000  12107.941176  12111.764706  12109.722222

            18ma_before2   19ma_before  19ma_before2  20ma_before  \
Date
2024-05-13           NaN           NaN           NaN          NaN
2024-05-14           NaN           NaN           NaN          NaN
2024-05-16           NaN           NaN           NaN          NaN
2024-05-17           NaN           NaN           NaN          NaN
2024-05-20           NaN           NaN           NaN          NaN
...                  ...           ...           ...          ...
2024-09-30  12127.222222  12118.684211  12125.000000     12117.00
2024-10-02  12123.333333  12110.789474  12118.684211     12107.00
2024-10-04  12114.722222  12108.947368  12110.789474     12105.50
2024-10-07  12114.166667  12111.578947  12108.947368     12106.75
2024-10-08  12113.611111  12111.578947  12111.578947     12109.75

            20ma_before2
Date
2024-05-13           NaN
2024-05-14           NaN
2024-05-16           NaN
2024-05-17           NaN
2024-05-20           NaN
...                  ...
2024-09-30      12119.25
2024-10-02      12117.00
2024-10-04      12107.00
2024-10-07      12105.50
2024-10-08      12106.75

[99 rows x 42 columns]
              open    high     low   close  volume  prevClose     3ma_before  \
Date
2024-05-13  110636  110910  110541  110801  110314        NaN            NaN
2024-05-14  110726  110785  110601  110781  157700   110801.0            NaN
2024-05-16  112099  112263  111480  111510  172413   110781.0            NaN
2024-05-17  111434  112188  111369  111979  131904   111510.0  111030.666667
2024-05-20  111979  112328  111929  112134  123510   111979.0  111423.333333
...            ...     ...     ...     ...     ...        ...            ...
2024-09-30  117255  117255  116010  116205  173024   117815.0  118403.333333
2024-10-02  116205  116465  115765  115915  109392   116205.0  117875.000000
2024-10-04  117370  118055  117250  117775  106852   115915.0  116645.000000
2024-10-07  120005  120350  119800  120055  267124   117775.0  116631.666667
2024-10-08  118940  119225  118670  118990  287391   120055.0  117915.000000

              3ma_before2  4ma_before  4ma_before2  ...  16ma_before  \
Date                                                ...
2024-05-13            NaN         NaN          NaN  ...          NaN
2024-05-14            NaN         NaN          NaN  ...          NaN
2024-05-16            NaN         NaN          NaN  ...          NaN
2024-05-17            NaN         NaN          NaN  ...          NaN
2024-05-20  111030.666667   111267.75          NaN  ...          NaN
...                   ...         ...          ...  ...          ...
2024-09-30  118546.666667   118363.75    118471.25  ...  115151.5625
2024-10-02  118403.333333   117853.75    118363.75  ...  115131.8750
2024-10-04  117875.000000   117385.00    117853.75  ...  115333.7500
2024-10-07  116645.000000   116927.50    117385.00  ...  115672.8125
2024-10-08  116631.666667   117487.50    116927.50  ...  116223.4375

            16ma_before2    17ma_before   17ma_before2    18ma_before  \
Date
2024-05-13           NaN            NaN            NaN            NaN
2024-05-14           NaN            NaN            NaN            NaN
2024-05-16           NaN            NaN            NaN            NaN
2024-05-17           NaN            NaN            NaN            NaN
2024-05-20           NaN            NaN            NaN            NaN
...                  ...            ...            ...            ...
2024-09-30   115067.1875  115228.823529  115097.352941  115248.333333
2024-10-02   115151.5625  115213.529412  115228.823529  115283.055556
2024-10-04   115131.8750  115177.941176  115213.529412  115252.500000
2024-10-07   115333.7500  115477.352941  115177.941176  115322.222222
2024-10-08   115672.8125  115930.588235  115477.352941  115731.666667

             18ma_before2    19ma_before   19ma_before2  20ma_before  \
Date
2024-05-13            NaN            NaN            NaN          NaN
2024-05-14            NaN            NaN            NaN          NaN
2024-05-16            NaN            NaN            NaN          NaN
2024-05-17            NaN            NaN            NaN          NaN
2024-05-20            NaN            NaN            NaN          NaN
...                   ...            ...            ...          ...
2024-09-30  115056.944444  115202.105263  115145.000000    115278.50
2024-10-02  115248.333333  115298.684211  115202.105263    115252.25
2024-10-04  115283.055556  115316.315789  115298.684211    115329.50
2024-10-07  115252.500000  115385.263158  115316.315789    115439.25
2024-10-08  115322.222222  115571.315789  115385.263158    115618.75

            20ma_before2
Date
2024-05-13           NaN
2024-05-14           NaN
2024-05-16           NaN
2024-05-17           NaN
2024-05-20           NaN
...                  ...
2024-09-30     115177.50
2024-10-02     115278.50
2024-10-04     115252.25
2024-10-07     115329.50
2024-10-08     115439.25

[99 rows x 42 columns]
             open   high    low  close  volume  prevClose    3ma_before  \
Date
2024-05-13  14705  14735  14640  14665   66604        NaN           NaN
2024-05-14  14570  14610  14545  14585   36924    14665.0           NaN
2024-05-16  14870  14930  14865  14870  126756    14585.0           NaN
2024-05-17  14815  14855  14780  14855   61083    14870.0  14706.666667
2024-05-20  15065  15260  15045  15210  231024    14855.0  14770.000000
...           ...    ...    ...    ...     ...        ...           ...
2024-09-30  16325  16335  16220  16290   93131    16340.0  16311.666667
2024-10-02  16295  16305  16200  16225   92661    16290.0  16313.333333
2024-10-04  16245  16335  16245  16315  209796    16225.0  16285.000000
2024-10-07  16230  16235  16165  16165  111992    16315.0  16276.666667
2024-10-08  16170  16210  16120  16170  125670    16165.0  16235.000000

             3ma_before2  4ma_before  4ma_before2  ...  16ma_before  \
Date                                               ...
2024-05-13           NaN         NaN          NaN  ...          NaN
2024-05-14           NaN         NaN          NaN  ...          NaN
2024-05-16           NaN         NaN          NaN  ...          NaN
2024-05-17           NaN         NaN          NaN  ...          NaN
2024-05-20  14706.666667    14743.75          NaN  ...          NaN
...                  ...         ...          ...  ...          ...
2024-09-30  16238.333333    16263.75     16205.00  ...   15738.1250
2024-10-02  16311.666667    16306.25     16263.75  ...   15796.5625
2024-10-04  16313.333333    16291.25     16306.25  ...   15854.0625
2024-10-07  16285.000000    16292.50     16291.25  ...   15911.5625
2024-10-08  16276.666667    16248.75     16292.50  ...   15954.3750

            16ma_before2   17ma_before  17ma_before2   18ma_before  \
Date
2024-05-13           NaN           NaN           NaN           NaN
2024-05-14           NaN           NaN           NaN           NaN
2024-05-16           NaN           NaN           NaN           NaN
2024-05-17           NaN           NaN           NaN           NaN
2024-05-20           NaN           NaN           NaN           NaN
...                  ...           ...           ...           ...
2024-09-30    15677.5000  15716.470588  15666.470588  15703.888889
2024-10-02    15738.1250  15770.588235  15716.470588  15748.333333
2024-10-04    15796.5625  15821.764706  15770.588235  15795.833333
2024-10-07    15854.0625  15881.176471  15821.764706  15849.166667
2024-10-08    15911.5625  15926.470588  15881.176471  15896.944444

            18ma_before2   19ma_before  19ma_before2  20ma_before  \
Date
2024-05-13           NaN           NaN           NaN          NaN
2024-05-14           NaN           NaN           NaN          NaN
2024-05-16           NaN           NaN           NaN          NaN
2024-05-17           NaN           NaN           NaN          NaN
2024-05-20           NaN           NaN           NaN          NaN
...                  ...           ...           ...          ...
2024-09-30  15657.222222  15693.157895  15645.263158     15680.00
2024-10-02  15703.888889  15734.736842  15693.157895     15723.00
2024-10-04  15748.333333  15773.421053  15734.736842     15759.25
2024-10-07  15795.833333  15823.157895  15773.421053     15800.50
2024-10-08  15849.166667  15865.789474  15823.157895     15840.25

            20ma_before2
Date
2024-05-13           NaN
2024-05-14           NaN
2024-05-16           NaN
2024-05-17           NaN
2024-05-20           NaN
...                  ...
2024-09-30      15637.50
2024-10-02      15680.00
2024-10-04      15723.00
2024-10-07      15759.25
2024-10-08      15800.50

[99 rows x 42 columns]

'\n    #200거래일 평균 모멘텀\n    specific_days = list()\n\n    for i in range(1,11):\n        st = i * 20\n        specific_days.append(st)\n\n    for day in specific_days:\n        column_name = f\'Momentum_{day}\'\n        df[column_name] = (df[\'prevClose\'] > df[\'close\'].shift(day)).astype(int)\n\n    df[\'Average_Momentum\'] = df[[f\'Momentum_{day}\' for day in specific_days]].sum(axis=1) / 10\n    \n    df.dropna(inplace=True) #데이터 없는건 날린다!\n\n    data_dict = {stock_code: df}\n    stock_df_list.append(data_dict)\n        \n    print("---stock_code---", stock_code , " len ",len(df))\n    \n    pprint.pprint(df)\n\ncombined_df = pd.concat([list(data_dict.values())[0].assign(stock_code=stock_code) for data_dict in stock_df_list for stock_code in data_dict])\ncombined_df.sort_index(inplace=True)\npprint.pprint(combined_df)\nprint(" len(combined_df) ", len(combined_df))\n\ndate = combined_df.iloc[-1].name\n'